### ISSUE TITLE
MySQL can't run

### ISSUE THREAD

**Issue by wei98k** [leocavalcante/Docktober#4]
## env 
- ProductName:	Mac OS X
- ProductVersion:	10.13.1
- BuildVersion:	17B1003

- Docker version 18.03.1-ce, build 9ee9f40
- docker-compose version 1.21.1, build 5a3f1a3

## step

`docker-compose logs docktober_db`

```
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```

**Comment by leocavalcante** [comment]
You error message says that it could not find a configuration file. By default, `docker-compose` will look for the file in the directory were it is running. To tell `docker-compose` to use a config file located elsewhere you can use the `-f` option. If you followed the steps on README and cloned this repository inside a `.docker` directory, there is where the `docker-compose.yml` is located, so your command should look like:

```bash
docker-compose -f .docker/docker-compose.yml logs
```

**Comment by leocavalcante** [comment]
Despite that, don't forget that using a database will require a few additional steps described right bellow *if you want some database power* section at the README file.

**Comment by wei98k** [comment]
`docker-compose -f .docker/docker-compose.yml logs`

```
docktober_db | error: database is uninitialized and password option is not specified
docktober_db |   You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

Where is the variable configured?

**Comment by leocavalcante** [comment]
Please, review the [README](https://github.com/leocavalcante/Docktober/blob/master/README.md) file. Look for the section described as [If you want some database power](https://github.com/leocavalcante/Docktober#if-you-want-some-database-power). It explains what you should do to have a `.env` file where you can set the `DB_PASSWORD`.

**Comment by leocavalcante** [comment]
Closing due inactivity.
