### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by mjosborne1** [leocavalcante/Docktober#6]
Hello,,
Thanks for this git repo.
I am no docker expert, just someone who wants to set up ocktobercms in a simple way.
I would like some more clarification in the README about what is required to setup the mysql database.
I have tried using a .env file in the .docker folder and the parent of the docker folder.

My .env file:
DB_HOST=db
DB_DATABASE=db_octobercms
DB_USERNAME=root 
DB_PASSWORD=SomePassword

 I get the following errors when I run this:

$ docker-compose -f .docker/docker-compose.yml exec php php artisan october:up

Errors:
Migrating application and plugins...

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema =
   database and table_name = migrations)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [2002] No such file or directory

  [PDOException]
  SQLSTATE[HY000] [2002] No such file or directory

**Comment by leocavalcante** [comment]
Did you ran `docker-compose -f .docker/docker-compose.yml up -d --build` after .env setup?

**Comment by leocavalcante** [comment]
Closing due lack of activity.
