### ISSUE TITLE
Can not connect to database

### ISSUE THREAD

**Issue by csongorkeller** [leocavalcante/Docktober#7]
Hi,
I have set up everything based on the readme. One of the last step is "Set .env's DB_HOST to db and add some value for DB_PASSWORD"
I have run Mamp with MySQL db, added the correct credentials to .env, but if I open /backend page, gives me an error: database is missing
And that is why I can not perform the last 2 steps:
1. docker-compose -f .docker/docker-compose.yml up -d --build
2. docker-compose -f .docker/docker-compose.yml exec php php artisan october:up

Anyway everything works perfectly except this issue, and the app did not open on the machine IP, but on 0.0.0.0:8000

Can you help me out? What did I wrong?
Thanks

**Comment by csongorkeller** [comment]
Well basically after typing _docker-compose -f .docker/docker-compose.yml exec php php artisan october:up_ got this error:
<img width="1280" alt="Screenshot 2019-07-24 at 17 19 47" src="https://user-images.githubusercontent.com/44320707/61806033-44126000-ae37-11e9-9abc-951f9219c446.png">

**Comment by arelstone** [comment]
I am experiencing the same.. Tried a few times now..

**Comment by arelstone** [comment]
@csongorkeller I am experienced the same error message... 

What I did to fix this was removing the containers and building them again. By doing this i was able to run the `october:up` command

```
docker-compose -f .docker/docker-compose.yml rm
docker-compose -f .docker/docker-compose.yml up -d --build
docker-compose -f .docker/docker-compose.yml exec php php artisan october:up
```

**Comment by leocavalcante** [comment]
@csongorkeller, did @arelstone's suggestion fixed it?

**Comment by csongorkeller** [comment]
Yeah, thanks guys. That fixed my issue. Cheers
